class ListOfBibleBooksConstante {
  static const List<String> bookNames = [
    "genesis.json",
    "exodo.json",
    "levitico.json",
    "numeros.json",
    "deuteronomio.json",
    "josue.json",
    "juizes.json",
    "rute.json",
    "1 samuel.json",
    "2 samuel.json",
    "1 reis.json",
    "2 reis.json",
    "1 cronicas.json",
    "2 cronicas.json",
    "esdras.json",
    "neemias.json",
    "ester.json",
    "jo.json",
    "salmos.json",
    "proverbios.json",
    "eclesiastes.json",
    "canticos.json",
    "isaias.json",
    "jeremias.json",
    "lamentacoes de jeremias.json",
    "ezequiel.json",
    "daniel.json",
    "oseias.json",
    "joel.json",
    "amos.json",
    "obadias.json",
    "jonas.json",
    "miqueias.json",
    "naum.json",
    "habacuque.json",
    "sofonias.json",
    "ageu.json",
    "zacarias.json",
    "malaquias.json",
    "mateus.json",
    "marcos.json",
    "lucas.json",
    "joao.json",
    "atos.json",
    "romanos.json",
    "1 corintios.json",
    "2 corintios.json",
    "galatas.json",
    "efesios.json",
    "filipenses.json",
    "colossenses.json",
    "1 tessalonicenses.json",
    "2 tessalonicenses.json",
    "1 timoteo.json",
    "2 timoteo.json",
    "tito.json",
    "filemom.json",
    "hebreus.json",
    "tiago.json",
    "1 pedro.json",
    "2 pedro.json",
    "1_joao.json",
    "2 joao.json",
    "3 joao.json",
    "judas.json",
    "apocalipse.json"
  ];
}
